/** Card Hedge upstream 라우트 목록 (api-1.json 기준) */
export type CardhedgerApiRoute = {
  method: 'GET' | 'POST';
  upstreamPath: string;
  localPath: string;
  handler: string;
  summary: string;
  description: string;
  pathParams: string[];
  queryParams: string[];
  binary: boolean;
  tag: string;
};

export const CARDHEDGER_API_ROUTES: CardhedgerApiRoute[] = [
  {
    method: 'GET',
    upstreamPath: '/v1/cards/top-movers',
    localPath: 'v1/cards/top-movers',
    handler: 'getCardsTopMovers',
    summary: "주간 상승률 상위 카드",
    description: "지난 1주일 가격 상승률이 높은 카드 목록입니다. 1시간 캐시.",
    pathParams: [],
    queryParams: ["count","category"],
    binary: false,
    tag: 'cardhedger',
  },
  {
    method: 'POST',
    upstreamPath: '/v1/cards/card-search',
    localPath: 'v1/cards/card-search',
    handler: 'postCardsCardSearch',
    summary: "카드 검색",
    description: "검색어·세트·카테고리·선수 등으로 카드를 검색합니다.",
    pathParams: [],
    queryParams: [],
    binary: false,
    tag: 'cardhedger',
  },
  {
    method: 'POST',
    upstreamPath: '/v1/cards/card-match',
    localPath: 'v1/cards/card-match',
    handler: 'postCardsCardMatch',
    summary: "AI 카드 매칭",
    description: "자연어 설명으로 가장 적합한 카드 1건과 신뢰도를 반환합니다.",
    pathParams: [],
    queryParams: [],
    binary: false,
    tag: 'cardhedger',
  },
  {
    method: 'POST',
    upstreamPath: '/v1/cards/set-search',
    localPath: 'v1/cards/set-search',
    handler: 'postCardsSetSearch',
    summary: "세트 검색",
    description: "카드 세트 이름·카테고리로 세트를 검색합니다.",
    pathParams: [],
    queryParams: [],
    binary: false,
    tag: 'cardhedger',
  },
  {
    method: 'POST',
    upstreamPath: '/v1/cards/search-cards-wsort',
    localPath: 'v1/cards/search-cards-wsort',
    handler: 'postCardsSearchCardsWsort',
    summary: "정렬 포함 카드 검색",
    description: "전문 검색·필터·정렬·페이지네이션으로 카드를 검색합니다.",
    pathParams: [],
    queryParams: [],
    binary: false,
    tag: 'cardhedger',
  },
  {
    method: 'POST',
    upstreamPath: '/v1/cards/card-details',
    localPath: 'v1/cards/card-details',
    handler: 'postCardsCardDetails',
    summary: "카드 ID 상세 조회",
    description: "card_id로 카드 상세 정보를 조회합니다.",
    pathParams: [],
    queryParams: [],
    binary: false,
    tag: 'cardhedger',
  },
  {
    method: 'POST',
    upstreamPath: '/v1/cards/prices-by-cert',
    localPath: 'v1/cards/prices-by-cert',
    handler: 'postCardsPricesByCert',
    summary: "cert 번호 가격 조회",
    description: "PSA 등 grader cert 번호로 카드 정보와 가격을 조회합니다.",
    pathParams: [],
    queryParams: [],
    binary: false,
    tag: 'cardhedger',
  },
  {
    method: 'POST',
    upstreamPath: '/v1/cards/batch-prices-by-cert',
    localPath: 'v1/cards/batch-prices-by-cert',
    handler: 'postCardsBatchPricesByCert',
    summary: "cert 배치 가격 조회",
    description: "여러 cert 번호의 가격 추정치를 한 번에 조회합니다.",
    pathParams: [],
    queryParams: [],
    binary: false,
    tag: 'cardhedger',
  },
  {
    method: 'POST',
    upstreamPath: '/v1/cards/prices-by-cert-ocr',
    localPath: 'v1/cards/prices-by-cert-ocr',
    handler: 'postCardsPricesByCertOcr',
    summary: "슬랩 이미지 OCR 가격",
    description: "슬랩 사진에서 cert를 읽어 가격을 조회합니다.",
    pathParams: [],
    queryParams: [],
    binary: false,
    tag: 'cardhedger',
  },
  {
    method: 'POST',
    upstreamPath: '/v1/cards/details-by-cert-ocr',
    localPath: 'v1/cards/details-by-cert-ocr',
    handler: 'postCardsDetailsByCertOcr',
    summary: "슬랩 이미지 OCR 상세",
    description: "슬랩 사진에서 cert를 읽어 카드 상세를 조회합니다.",
    pathParams: [],
    queryParams: [],
    binary: false,
    tag: 'cardhedger',
  },
  {
    method: 'POST',
    upstreamPath: '/v1/cards/details-by-certs',
    localPath: 'v1/cards/details-by-certs',
    handler: 'postCardsDetailsByCerts',
    summary: "cert 배치 상세 조회",
    description: "여러 cert 번호의 카드 상세를 한 번에 조회합니다.",
    pathParams: [],
    queryParams: [],
    binary: false,
    tag: 'cardhedger',
  },
  {
    method: 'POST',
    upstreamPath: '/v1/cards/prices-by-card',
    localPath: 'v1/cards/prices-by-card',
    handler: 'postCardsPricesByCard',
    summary: "카드 ID 가격 이력",
    description: "card_id·등급별 가격 이력(기본 180일, 최대 365일)을 조회합니다.",
    pathParams: [],
    queryParams: [],
    binary: false,
    tag: 'cardhedger',
  },
  {
    method: 'POST',
    upstreamPath: '/v1/cards/comps',
    localPath: 'v1/cards/comps',
    handler: 'postCardsComps',
    summary: "비교 판매가 (COMPS)",
    description: "최근 거래 기반 비교 가격과 raw 거래 목록을 반환합니다.",
    pathParams: [],
    queryParams: [],
    binary: false,
    tag: 'cardhedger',
  },
  {
    method: 'POST',
    upstreamPath: '/v1/cards/all-prices-by-card',
    localPath: 'v1/cards/all-prices-by-card',
    handler: 'postCardsAllPricesByCard',
    summary: "전 등급 최신 가격",
    description: "카드의 모든 등급·그레이더별 최신 가격을 조회합니다.",
    pathParams: [],
    queryParams: [],
    binary: false,
    tag: 'cardhedger',
  },
  {
    method: 'POST',
    upstreamPath: '/v1/cards/90day-prices-by-grade',
    localPath: 'v1/cards/90day-prices-by-grade',
    handler: 'postCards90dayPricesByGrade',
    summary: "등급별 90일 평균 가격",
    description: "특정 등급의 90일 평균 가격 카드 목록입니다.",
    pathParams: [],
    queryParams: [],
    binary: false,
    tag: 'cardhedger',
  },
  {
    method: 'POST',
    upstreamPath: '/v1/cards/card-request',
    localPath: 'v1/cards/card-request',
    handler: 'postCardsCardRequest',
    summary: "카드 등록 요청",
    description: "상업 계약이 있는 경우 신규 카드 등록을 요청합니다.",
    pathParams: [],
    queryParams: [],
    binary: false,
    tag: 'cardhedger',
  },
  {
    method: 'POST',
    upstreamPath: '/v1/cards/price-updates',
    localPath: 'v1/cards/price-updates',
    handler: 'postCardsPriceUpdates',
    summary: "가격 변경 델타 조회",
    description: "지정 시각 이후 변경된 가격만 조회합니다(델타 폴링).",
    pathParams: [],
    queryParams: [],
    binary: false,
    tag: 'cardhedger',
  },
  {
    method: 'POST',
    upstreamPath: '/v1/cards/price-estimate',
    localPath: 'v1/cards/price-estimate',
    handler: 'postCardsPriceEstimate',
    summary: "가격 추정",
    description: "카드·등급의 가격 추정치를 조회합니다.",
    pathParams: [],
    queryParams: [],
    binary: false,
    tag: 'cardhedger',
  },
  {
    method: 'POST',
    upstreamPath: '/v1/cards/batch-price-estimate',
    localPath: 'v1/cards/batch-price-estimate',
    handler: 'postCardsBatchPriceEstimate',
    summary: "배치 가격 추정",
    description: "여러 카드의 가격 추정치를 한 번에 조회합니다.",
    pathParams: [],
    queryParams: [],
    binary: false,
    tag: 'cardhedger',
  },
  {
    method: 'POST',
    upstreamPath: '/v1/cards/card-fmv',
    localPath: 'v1/cards/card-fmv',
    handler: 'postCardsCardFmv',
    summary: "공정 시장가 (FMV)",
    description: "카드·등급의 FMV(신뢰도·불확실성 밴드 포함)를 조회합니다.",
    pathParams: [],
    queryParams: [],
    binary: false,
    tag: 'cardhedger',
  },
  {
    method: 'POST',
    upstreamPath: '/v1/cards/card-fmv-batch',
    localPath: 'v1/cards/card-fmv-batch',
    handler: 'postCardsCardFmvBatch',
    summary: "FMV 배치 조회",
    description: "여러 카드·등급의 FMV를 한 번에 조회합니다.",
    pathParams: [],
    queryParams: [],
    binary: false,
    tag: 'cardhedger',
  },
  {
    method: 'POST',
    upstreamPath: '/v1/cards/fmv-by-cert',
    localPath: 'v1/cards/fmv-by-cert',
    handler: 'postCardsFmvByCert',
    summary: "cert FMV 조회",
    description: "cert 번호로 FMV를 조회합니다.",
    pathParams: [],
    queryParams: [],
    binary: false,
    tag: 'cardhedger',
  },
  {
    method: 'POST',
    upstreamPath: '/v1/cards/subscribe-price-updates',
    localPath: 'v1/cards/subscribe-price-updates',
    handler: 'postCardsSubscribePriceUpdates',
    summary: "가격 업데이트 구독",
    description: "가격 변경 웹훅/구독을 등록합니다.",
    pathParams: [],
    queryParams: [],
    binary: false,
    tag: 'cardhedger',
  },
  {
    method: 'POST',
    upstreamPath: '/v1/cards/90day-prices-by-grade-search',
    localPath: 'v1/cards/90day-prices-by-grade-search',
    handler: 'postCards90dayPricesByGradeSearch',
    summary: "90일 가격 검색",
    description: "90일 가격 데이터가 있는 카드를 검색합니다.",
    pathParams: [],
    queryParams: [],
    binary: false,
    tag: 'cardhedger',
  },
  {
    method: 'POST',
    upstreamPath: '/v1/cards/additions-summary',
    localPath: 'v1/cards/additions-summary',
    handler: 'postCardsAdditionsSummary',
    summary: "신규 카탈로그 추가 요약",
    description: "기간별 신규 카탈로그 추가 통계입니다.",
    pathParams: [],
    queryParams: [],
    binary: false,
    tag: 'cardhedger',
  },
  {
    method: 'POST',
    upstreamPath: '/v1/cards/total-sales-by-player',
    localPath: 'v1/cards/total-sales-by-player',
    handler: 'postCardsTotalSalesByPlayer',
    summary: "선수별 총 판매 건수",
    description: "선수별 누적 판매 건수를 조회합니다.",
    pathParams: [],
    queryParams: [],
    binary: false,
    tag: 'cardhedger',
  },
  {
    method: 'POST',
    upstreamPath: '/v1/cards/sales-stats-by-player',
    localPath: 'v1/cards/sales-stats-by-player',
    handler: 'postCardsSalesStatsByPlayer',
    summary: "선수별 판매 통계",
    description: "선수별 판매 건수·합계·평균 통계입니다.",
    pathParams: [],
    queryParams: [],
    binary: false,
    tag: 'cardhedger',
  },
  {
    method: 'POST',
    upstreamPath: '/v1/cards/image-search',
    localPath: 'v1/cards/image-search',
    handler: 'postCardsImageSearch',
    summary: "이미지 카드 검색",
    description: "카드 이미지로 유사 카드를 검색합니다.",
    pathParams: [],
    queryParams: [],
    binary: false,
    tag: 'cardhedger',
  },
  {
    method: 'POST',
    upstreamPath: '/v1/cards/image-match',
    localPath: 'v1/cards/image-match',
    handler: 'postCardsImageMatch',
    summary: "이미지 카드 식별",
    description: "이미지 한 장으로 카드를 식별합니다.",
    pathParams: [],
    queryParams: [],
    binary: false,
    tag: 'cardhedger',
  },
  {
    method: 'POST',
    upstreamPath: '/v1/cards/issues',
    localPath: 'v1/cards/issues',
    handler: 'postCardsIssues',
    summary: "데이터 이슈",
    description: "GET: 이슈 목록 · POST: 데이터 이슈 제출",
    pathParams: [],
    queryParams: [],
    binary: false,
    tag: 'cardhedger',
  },
  {
    method: 'GET',
    upstreamPath: '/v1/cards/issues',
    localPath: 'v1/cards/issues',
    handler: 'getCardsIssues',
    summary: "데이터 이슈",
    description: "GET: 이슈 목록 · POST: 데이터 이슈 제출",
    pathParams: [],
    queryParams: ["status"],
    binary: false,
    tag: 'cardhedger',
  },
  {
    method: 'GET',
    upstreamPath: '/v1/cards/issues/{issue_id}',
    localPath: 'v1/cards/issues/{issue_id}',
    handler: 'getCardsIssuesByissue_id',
    summary: "이슈 상세 조회",
    description: "제출한 데이터 이슈의 상세 내용을 조회합니다.",
    pathParams: ["issue_id"],
    queryParams: [],
    binary: false,
    tag: 'cardhedger',
  },
  {
    method: 'GET',
    upstreamPath: '/v1/download/daily-price-export/{file_date}',
    localPath: 'v1/download/daily-price-export/{file_date}',
    handler: 'getDownloadDailyPriceExportByfile_date',
    summary: "일별 가격 CSV 다운로드",
    description: "Elite/Enterprise 전용 일별 가격 CSV 파일입니다.",
    pathParams: ["file_date"],
    queryParams: [],
    binary: true,
    tag: 'cardhedger',
  },
];
