#!/usr/bin/env bash
# Cloud Agent install phase — idempotent repository bootstrap.
# Installs local infra (Postgres + Redis), project dependencies, and dev env files.
# Runs after checkout; safe to run repeatedly. Long-running daemons live in start.sh.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

echo "[install] repo root: $ROOT"

# 1) System packages — Postgres 16 + Redis. Stable deps; installed once, captured
#    into the environment snapshot/base. apt install is idempotent.
if ! command -v pg_ctlcluster >/dev/null 2>&1 || ! command -v redis-server >/dev/null 2>&1; then
  echo "[install] installing postgresql + redis-server"
  sudo apt-get update -y
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
    postgresql postgresql-contrib redis-server
else
  echo "[install] postgresql + redis-server already present"
fi

# 2) Node dependencies. Pin pnpm via corepack so installs are deterministic
#    regardless of the VM's default pnpm (corepack may otherwise serve a newer
#    major with incompatible node_modules handling). CI=true keeps it
#    non-interactive (auto-confirms module purge, treats ignored dep build
#    scripts as a warning rather than a fatal error).
PNPM="corepack pnpm@10.33.3"
export CI=true
corepack enable >/dev/null 2>&1 || true
echo "[install] pnpm install (backend)"
( cd backend && $PNPM install --frozen-lockfile )
echo "[install] pnpm install (frontend)"
( cd frontend && $PNPM install --frozen-lockfile )
echo "[install] pnpm install (contracts)"
( cd contracts && $PNPM install --frozen-lockfile )

# 3) Dev env files — gitignored, created only when missing (never overwrite).
#    Values are non-sensitive local placeholders. Replace Privy/Pinata/Cardhedger/
#    PSA keys and chain addresses with real values for full feature testing.
if [ ! -f backend/.env ]; then
  echo "[install] writing backend/.env"
  cat > backend/.env <<'EOF'
# Local dev — generated by .cursor/install.sh. Gitignored; not committed.
PORT=4100
NODE_ENV=development
CORS_ORIGIN=http://localhost:3000
FRONTEND_URL=http://localhost:3000

POSTGRES_HOST=localhost
POSTGRES_PORT=5432
POSTGRES_USER=tokenable
POSTGRES_PASSWORD=tokenable
POSTGRES_DB=tokenable

REDIS_URL=redis://127.0.0.1:6379

JWT_SECRET=dev_jwt_secret_change_me_0123456789

# IPFS (Pinata) — placeholders so the module boots; set real values for uploads.
PINATA_JWT=dev_placeholder_pinata_jwt
PINATA_GATEWAY=dev.mypinata.cloud

# Blockchain (Ethereum Sepolia — default dev chain, public RPC).
# RWA address is a placeholder; deploy a contract and set the real address for
# on-chain reads/writes (see docs/guides/local-setup.md).
DEFAULT_CHAIN_ID=11155111
CHAIN_11155111_RPC_URL=https://ethereum-sepolia-rpc.publicnode.com
CHAIN_11155111_RWA_ADDRESS=0x0000000000000000000000000000000000000001
CHAIN_11155111_USDC_ADDRESS=0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238

# Marketplace admin console (dev defaults; login skyand / 071725).
MARKETPLACE_ADMIN_USERNAME=skyand
MARKETPLACE_ADMIN_PASSWORD=071725
MARKETPLACE_ADMIN_SESSION_SECRET=dev_marketplace_admin_secret_0123456789

# Background workers off in local dev.
MARKET_SNAPSHOT_CRON_ENABLED=false
CARD_TOP100_CRON_ENABLED=false
CARDLADDER_INDEXES_PREWARM_ENABLED=false
IDENTITY_RECONCILIATION_ENABLED=false
PORTFOLIO_SNAPSHOT_CRON_ENABLED=false
EOF
else
  echo "[install] backend/.env exists — leaving as-is"
fi

if [ ! -f frontend/.env ]; then
  echo "[install] writing frontend/.env"
  cat > frontend/.env <<'EOF'
# Local dev — generated by .cursor/install.sh. Gitignored; not committed.
# NEXT_PUBLIC_* are embedded at build time; restart `pnpm dev` after changes.
NEXT_PUBLIC_DEFAULT_CHAIN_ID=11155111
NEXT_PUBLIC_CHAIN_11155111_RPC_URL=https://ethereum-sepolia-rpc.publicnode.com
NEXT_PUBLIC_CHAIN_11155111_RWA=0x0000000000000000000000000000000000000001
NEXT_PUBLIC_CHAIN_11155111_USDC=0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238

NEXT_PUBLIC_PLATFORM_FEE_RECIPIENT=0x0000000000000000000000000000000000000001
NEXT_PUBLIC_PLATFORM_FEE_BPS=500

# Privy App ID (public, client-embedded). The provider tree — which also mounts
# the shared React Query client — only initializes with a 25-char App ID, so a
# valid-length placeholder is required for pages to render in dev. Replace with a
# real Privy App ID from the Privy dashboard to enable working login.
NEXT_PUBLIC_PRIVY_APP_ID=cldevtokenable00000000abc
EOF
else
  echo "[install] frontend/.env exists — leaving as-is"
fi

# 4) Postgres role + database (idempotent). Start the cluster just long enough to
#    provision; start.sh owns the per-boot daemon lifecycle.
sudo pg_ctlcluster 16 main start 2>/dev/null || true
for _ in $(seq 1 30); do
  sudo -u postgres pg_isready >/dev/null 2>&1 && break
  sleep 1
done

if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='tokenable'" | grep -q 1; then
  echo "[install] creating role tokenable"
  sudo -u postgres psql -c "CREATE ROLE tokenable LOGIN PASSWORD 'tokenable' SUPERUSER;"
fi
if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='tokenable'" | grep -q 1; then
  echo "[install] creating database tokenable"
  sudo -u postgres createdb -O tokenable tokenable
fi

echo "[install] done. Backend schema auto-syncs (TypeORM) on first boot."
