export const ETHERS_PROVIDER = 'ETHERS_PROVIDER';
export const USDC_CONTRACT = 'USDC_CONTRACT';
export const SKY_NFT_CONTRACT = 'SKY_NFT_CONTRACT';
export const MARKETPLACE_CONTRACT = 'MARKETPLACE_CONTRACT';
